import { build, context } from 'esbuild';
import { mkdir, copyFile, cp, readFile } from 'node:fs/promises';
const out = 'release/penbook';
await mkdir(out, { recursive: true });
const eraserBuild=await build({entryPoints:['src/erase-worker.ts'],bundle:true,write:false,format:'iife',platform:'browser',target:'es2022',minify:true});
const eraserSourcePlugin={name:'eraser-worker-source',setup(build){build.onResolve({filter:/^penbook:erase-worker$/},()=>({path:'eraser',namespace:'eraser-source'}));build.onLoad({filter:/.*/,namespace:'eraser-source'},()=>({contents:eraserBuild.outputFiles[0].text,loader:'text'}));}};
const workerSourcePlugin={name:'pdf-worker-source',setup(build){build.onLoad({filter:/[/\\]pdf\.worker\.mjs$/},async args=>({contents:await readFile(args.path,'utf8'),loader:'text'}));}};
const options = { entryPoints: ['src/main.ts'], bundle: true, external: ['obsidian','child_process'], loader: { '.svg': 'text' }, plugins:[workerSourcePlugin,eraserSourcePlugin], format: 'cjs', target: 'es2022', platform: 'browser', outfile: `${out}/main.js`, sourcemap: false, minify: true, logLevel: 'info', define: { 'process.env.NODE_ENV': '"production"' } };
await copyFile('manifest.json', `${out}/manifest.json`);
await copyFile('styles.css', `${out}/styles.css`);
await copyFile('LICENSE', `${out}/LICENSE`);
await copyFile('THIRD_PARTY_NOTICES.md', `${out}/THIRD_PARTY_NOTICES.md`);
await mkdir(`${out}/licenses`, { recursive: true });
await copyFile('node_modules/@phosphor-icons/core/LICENSE', `${out}/licenses/phosphor-icons.txt`);
await copyFile('node_modules/pdfjs-dist/LICENSE', `${out}/licenses/pdfjs.txt`);
await copyFile('node_modules/pdf-lib/LICENSE.md', `${out}/licenses/pdf-lib.txt`);
await copyFile('node_modules/perfect-freehand/LICENSE', `${out}/licenses/perfect-freehand.txt`);
await copyFile('node_modules/clipper-lib/clipper.js', `${out}/licenses/clipper-lib.js`);
await copyFile('licenses/clipper-lib-BSL-1.0.txt', `${out}/licenses/clipper-lib-BSL-1.0.txt`);
await copyFile('node_modules/polygon-clipping/LICENSE.md', `${out}/licenses/polygon-clipping.txt`);
await copyFile('node_modules/robust-predicates/LICENSE', `${out}/licenses/robust-predicates.txt`);
await copyFile('licenses/splaytree.txt', `${out}/licenses/splaytree.txt`);
await copyFile('node_modules/@pdf-lib/standard-fonts/LICENSE.md', `${out}/licenses/pdf-lib-standard-fonts.txt`);
await copyFile('node_modules/@pdf-lib/upng/LICENSE', `${out}/licenses/pdf-lib-upng.txt`);
await copyFile('node_modules/pako/LICENSE', `${out}/licenses/pako.txt`);
await copyFile('node_modules/tslib/LICENSE.txt', `${out}/licenses/tslib.txt`);
await cp('node_modules/pdfjs-dist/cmaps', `${out}/cmaps`, { recursive: true });
await cp('node_modules/pdfjs-dist/standard_fonts', `${out}/standard_fonts`, { recursive: true });
await cp('node_modules/pdfjs-dist/wasm', `${out}/wasm`, { recursive: true });
if (process.argv.includes('--watch')) { const ctx = await context(options); await ctx.watch(); } else await build(options);
