import { addIcon } from 'obsidian';
import penNibSvg from '@phosphor-icons/core/assets/regular/pen-nib.svg';
import eraserSvg from '@phosphor-icons/core/assets/regular/eraser.svg';
import lassoSvg from '@phosphor-icons/core/assets/regular/lasso.svg';
import shapesSvg from '@phosphor-icons/core/assets/regular/shapes.svg';
import textBoxSvg from '@phosphor-icons/core/assets/regular/textbox.svg';
import noteSvg from '@phosphor-icons/core/assets/regular/note-pencil.svg';
import linkSvg from '@phosphor-icons/core/assets/regular/link.svg';
import tableSvg from '@phosphor-icons/core/assets/regular/table.svg';
import handSvg from '@phosphor-icons/core/assets/regular/hand.svg';
import undoSvg from '@phosphor-icons/core/assets/regular/arrow-counter-clockwise.svg';
import redoSvg from '@phosphor-icons/core/assets/regular/arrow-clockwise.svg';
import plusSvg from '@phosphor-icons/core/assets/regular/plus.svg';
import importIconSvg from '@phosphor-icons/core/assets/regular/file-arrow-down.svg';
import exportIconSvg from '@phosphor-icons/core/assets/regular/file-arrow-up.svg';
import bookSvg from '@phosphor-icons/core/assets/regular/book-open.svg';
import fullscreenSvg from '@phosphor-icons/core/assets/regular/arrows-out.svg';
import moreSvg from '@phosphor-icons/core/assets/regular/dots-three.svg';
import sidebarSvg from '@phosphor-icons/core/assets/regular/sidebar-simple.svg';
import leftSvg from '@phosphor-icons/core/assets/regular/caret-left.svg';
import rightSvg from '@phosphor-icons/core/assets/regular/caret-right.svg';
import minusSvg from '@phosphor-icons/core/assets/regular/minus.svg';
import fitSvg from '@phosphor-icons/core/assets/regular/arrows-in.svg';
import copySvg from '@phosphor-icons/core/assets/regular/copy.svg';
import pasteSvg from '@phosphor-icons/core/assets/regular/clipboard.svg';
import trashSvg from '@phosphor-icons/core/assets/regular/trash.svg';
import paletteSvg from '@phosphor-icons/core/assets/regular/palette.svg';
import rotateSvg from '@phosphor-icons/core/assets/regular/arrow-clockwise.svg';
import frontSvg from '@phosphor-icons/core/assets/regular/selection-foreground.svg';
import backSvg from '@phosphor-icons/core/assets/regular/selection-background.svg';
import lockSvg from '@phosphor-icons/core/assets/regular/lock-simple.svg';
import unlockSvg from '@phosphor-icons/core/assets/regular/lock-simple-open.svg';
import groupSvg from '@phosphor-icons/core/assets/regular/bounding-box.svg';
import ungroupSvg from '@phosphor-icons/core/assets/regular/selection-slash.svg';
import editSvg from '@phosphor-icons/core/assets/regular/pencil-simple.svg';
import cropSvg from '@phosphor-icons/core/assets/regular/crop.svg';
import moveSvg from '@phosphor-icons/core/assets/regular/arrow-square-out.svg';
import bookmarkSvg from '@phosphor-icons/core/assets/regular/bookmark-simple.svg';
import notebookSvg from '@phosphor-icons/core/assets/regular/notebook.svg';
import settingsSvg from '@phosphor-icons/core/assets/regular/gear-six.svg';
import pdfSvg from '@phosphor-icons/core/assets/regular/file-pdf.svg';
import imageSvg from '@phosphor-icons/core/assets/regular/image.svg';
import fileSvg from '@phosphor-icons/core/assets/regular/file-text.svg';
import printSvg from '@phosphor-icons/core/assets/regular/printer.svg';
import searchSvg from '@phosphor-icons/core/assets/regular/magnifying-glass.svg';
import penSvg from '@phosphor-icons/core/assets/regular/pen.svg';
import brushSvg from '@phosphor-icons/core/assets/regular/paint-brush.svg';
import pencilSvg from '@phosphor-icons/core/assets/regular/pencil.svg';
import markerSvg from '@phosphor-icons/core/assets/regular/highlighter.svg';
import downSvg from '@phosphor-icons/core/assets/regular/caret-down.svg';
import rectangleSvg from '@phosphor-icons/core/assets/regular/rectangle.svg';
import circleSvg from '@phosphor-icons/core/assets/regular/circle.svg';
import triangleSvg from '@phosphor-icons/core/assets/regular/triangle.svg';
import arrowSvg from '@phosphor-icons/core/assets/regular/arrow-up-right.svg';
import selectAllSvg from '@phosphor-icons/core/assets/regular/selection-all.svg';
import checkSvg from '@phosphor-icons/core/assets/regular/check.svg';
import closeSvg from '@phosphor-icons/core/assets/regular/x.svg';
import tuneSvg from '@phosphor-icons/core/assets/regular/sliders-horizontal.svg';
import eyedropperSvg from '@phosphor-icons/core/assets/regular/eyedropper.svg';
import boldSvg from '@phosphor-icons/core/assets/regular/text-b.svg';
import italicSvg from '@phosphor-icons/core/assets/regular/text-italic.svg';
import alignLeftSvg from '@phosphor-icons/core/assets/regular/text-align-left.svg';
import alignCenterSvg from '@phosphor-icons/core/assets/regular/text-align-center.svg';
import alignRightSvg from '@phosphor-icons/core/assets/regular/text-align-right.svg';
import lineHeightSvg from '@phosphor-icons/core/assets/regular/arrows-vertical.svg';
import pinSvg from '@phosphor-icons/core/assets/regular/push-pin-simple.svg';
import tapeSvg from '@phosphor-icons/core/assets/regular/selection-background.svg';
import dotSvg from '@phosphor-icons/core/assets/regular/dot.svg';
import diamondSvg from '@phosphor-icons/core/assets/regular/diamond.svg';

/** Official Phosphor regular SVG outlines, kept in their native 256-unit coordinates. */
function outline(svg:string){return [...svg.matchAll(/<path\b[^>]*\bd="([^"]+)"/g)].map(match=>match[1]).join(' ');}
const penNib=outline(penNibSvg);
const eraser=outline(eraserSvg);
const lasso=outline(lassoSvg);
const shapes=outline(shapesSvg);
const textBox=outline(textBoxSvg);
const note=outline(noteSvg);
const link=outline(linkSvg);
const table=outline(tableSvg);
const hand=outline(handSvg);
const undo=outline(undoSvg);
const redo=outline(redoSvg);
const plus=outline(plusSvg);
const importIcon=outline(importIconSvg);
const exportIcon=outline(exportIconSvg);
const book=outline(bookSvg);
const fullscreen=outline(fullscreenSvg);
const more=outline(moreSvg);
const sidebar=outline(sidebarSvg);
const left=outline(leftSvg);
const right=outline(rightSvg);
const minus=outline(minusSvg);
const fit=outline(fitSvg);
const copy=outline(copySvg);
const paste=outline(pasteSvg);
const trash=outline(trashSvg);
const palette=outline(paletteSvg);
const rotate=outline(rotateSvg);
const front=outline(frontSvg);
const back=outline(backSvg);
const lock=outline(lockSvg);
const unlock=outline(unlockSvg);
const group=outline(groupSvg);
const ungroup=outline(ungroupSvg);
const edit=outline(editSvg);
const crop=outline(cropSvg);
const move=outline(moveSvg);
const bookmark=outline(bookmarkSvg);
const notebook=outline(notebookSvg);
const settings=outline(settingsSvg);
const pdf=outline(pdfSvg);
const image=outline(imageSvg);
const file=outline(fileSvg);
const print=outline(printSvg);
const search=outline(searchSvg);
const pen=outline(penSvg);
const brush=outline(brushSvg);
const pencil=outline(pencilSvg);
const marker=outline(markerSvg);
const down=outline(downSvg);
const rectangle=outline(rectangleSvg);
const circle=outline(circleSvg);
const triangle=outline(triangleSvg);
const arrow=outline(arrowSvg);
const selectAll=outline(selectAllSvg);
// The two requested custom symbols use the same 16-unit outline weight as Phosphor.
const laser='M62 184 144 102 168 126 86 208Q74 220 62 208L50 196Q44 190 62 184ZM73 195 156 112 150 106 67 189ZM174 54H190V80H174ZM208 88H234V104H208ZM196 66 208 54 220 66 208 78ZM180 116 192 128 180 140 168 128ZM148 62 160 74 148 86 136 74Z';
const rounded='M56 48H200A32 32 0 0 1 232 80V176A32 32 0 0 1 200 208H56A32 32 0 0 1 24 176V80A32 32 0 0 1 56 48ZM56 64A16 16 0 0 0 40 80V176A16 16 0 0 0 56 192H200A16 16 0 0 0 216 176V80A16 16 0 0 0 200 64Z';
const check=outline(checkSvg);
const close=outline(closeSvg);
const tune=outline(tuneSvg);
const eyedropper=outline(eyedropperSvg);
const bold=outline(boldSvg);
const italic=outline(italicSvg);
const alignLeft=outline(alignLeftSvg);
const alignCenter=outline(alignCenterSvg);
const alignRight=outline(alignRightSvg);
const lineHeight=outline(lineHeightSvg);
const pin=outline(pinSvg);
const tape=outline(tapeSvg);
const dot=outline(dotSvg);
const diamond=outline(diamondSvg);

export const ICONS={pen:penNib,eraser,lasso,shape:shapes,text:textBox,sticky:note,link,table,hand,undo,redo,plus,import:importIcon,export:exportIcon,read:book,fullscreen,more,sidebar,previous:left,next:right,minus,fit,copy,paste,delete:trash,palette,rotate,front,back,lock,unlock,group,ungroup,edit,crop,move,bookmark,notebook,settings,pdf,image,file,print,search};
export type IconName=keyof typeof ICONS;
export const ERASER_ICONS={stroke:eraser,pixel:eraser};
export const SELECT_ALL_ICON=selectAll;
export const LASER_ICON=laser;
export const UI_ICONS={check,close,tune,eyedropper,bold,italic,alignLeft,alignCenter,alignRight,lineHeight,pin,tape,dot};
export const PEN_ICONS={fountain:penNib,ballpoint:pen,brush,pencil,highlighter:marker};
export const SHAPE_ICONS={auto:shapes,rectangle,ellipse:circle,triangle,line:minus,arrow,diamond,rounded};
export function pathIcon(el:HTMLElement,pathData:string,size=20){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 256 256');svg.setAttribute('width',String(size));svg.setAttribute('height',String(size));svg.setAttribute('aria-hidden','true');svg.classList.add('pb-icon');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',pathData);path.setAttribute('fill','currentColor');svg.appendChild(path);el.appendChild(svg);return svg;}
export function registerIcons(){for(const[name,path]of Object.entries(ICONS))addIcon(`pb-${name}`,`<g transform="scale(0.390625)"><path fill="currentColor" stroke="none" d="${path}"/></g>`);}
export function icon(el:HTMLElement,name:IconName,size=20){return pathIcon(el,ICONS[name],size);}
export function dropdownIcon(el:HTMLElement){return pathIcon(el,down,18);}
export function actionIcon(title:string):IconName{
  if(title==='移动或复制选区到其他页')return 'move';
  const exact:Record<string,IconName>={'钢笔':'pen','橡皮擦':'eraser','套索选择':'lasso','形状':'shape','文本框':'text','便签':'sticky','链接':'link','表格':'table','平移':'hand','显示或隐藏页面列表':'sidebar','沉浸模式':'fullscreen','笔记本与页面选项':'more','上一页':'previous','下一页':'next','缩小':'minus','放大':'plus','适合宽度':'fit','移到顶层':'front','移到底层':'back','取消组合':'ungroup'};
  if(exact[title])return exact[title];
  if(title.startsWith('删除'))return 'delete';
  if(title==='更多书写工具')return 'more';
  if(title==='切换阅读与书写')return 'read';
  for(const [text,name]of [['撤销','undo'],['重做','redo'],['导入','import'],['导出','export'],['阅读','read'],['插入页面','plus'],['添加页面','plus'],['复制','copy'],['粘贴','paste'],['删除','delete'],['颜色','palette'],['旋转','rotate'],['解锁','unlock'],['锁定','lock'],['组合','group'],['编辑','edit'],['裁剪','crop'],['移动','move'],['打印','print'],['PDF','pdf'],['图片','image'],['书签','bookmark'],['索引','file'],['搜索','search']]as [string,IconName][])if(title.includes(text))return name;
  return 'settings';
}
